// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication4.Data;

#nullable disable

namespace WebApplication4.Migrations
{
    [DbContext(typeof(ProductTaskDbcontext))]
    partial class ProductTaskDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication4.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Customer1",
                            Surname = "Customer01"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Customer2",
                            Surname = "Customer02"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Customer3",
                            Surname = "Customer03"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Customer4",
                            Surname = "Customer04"
                        });
                });

            modelBuilder.Entity("WebApplication4.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 2,
                            OrderDate = new DateTime(2023, 12, 6, 4, 35, 35, 125, DateTimeKind.Local).AddTicks(458),
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 1,
                            OrderDate = new DateTime(2023, 12, 6, 4, 35, 35, 125, DateTimeKind.Local).AddTicks(475),
                            ProductId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 4,
                            OrderDate = new DateTime(2023, 12, 6, 4, 35, 35, 125, DateTimeKind.Local).AddTicks(477),
                            ProductId = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 3,
                            OrderDate = new DateTime(2023, 12, 6, 4, 35, 35, 125, DateTimeKind.Local).AddTicks(478),
                            ProductId = 4
                        });
                });

            modelBuilder.Entity("WebApplication4.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Discount = 10m,
                            Name = "Product1",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Discount = 20m,
                            Name = "Product2",
                            Price = 200m
                        },
                        new
                        {
                            Id = 3,
                            Discount = 30m,
                            Name = "Product3",
                            Price = 300m
                        },
                        new
                        {
                            Id = 4,
                            Discount = 40m,
                            Name = "Product4",
                            Price = 400m
                        });
                });

            modelBuilder.Entity("WebApplication4.Entities.Order", b =>
                {
                    b.HasOne("WebApplication4.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication4.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
